CREATE DATABASE Teorias_de_fanes;
USE Teorias_de_fanes;
CREATE TABLE Usuarios(
identificador INT PRIMARY KEY AUTO_INCREMENT,
columna_usuario VARCHAR (50) NOT NULL UNIQUE,
columna_password VARCHAR (255) NOT NULL,
mail VARCHAR (50) NOT NULL
);
CREATE TABLE Serie(
ID_SERIE INT PRIMARY KEY AUTO_INCREMENT,
Nombre VARCHAR (50) NOT NULL
);
CREATE TABLE Foro(
ID_FORO INT PRIMARY KEY AUTO_INCREMENT,
Titulo VARCHAR (50) NOT NULL,
Mensaje VARCHAR (500) NOT NULL,
Fecha DATE NOT NULL,
ID_SERIE INT FOREIGN KEY REFERENCES Serie(ID_SERIE),
identificador INT not null,
FOREIGN KEY identificador  REFERENCES Usuarios (identificador)
);
CREATE TABLE Respuestas(
ID_RESPUESTAS INT PRIMARY KEY AUTO_INCREMENT,
Mensaje VARCHAR (500) NOT NULL,
Fecha DATE NOT NULL,
identificador INT not null,
FOREIGN KEY identificador REFERENCES Usuarios(identificador),
ID_FORO int,
FOREIGN KEY ID_FORO REFERENCES Foro(ID_FORO)
);
